#!/usr/bin/zsh
#
# yle2m4v
#
# Download video file (with subtitles, if any) from Yle Areena
# and convert the downloaded FLV file into a M4V file
#
# Usage: yle2m4v [url]
#
# url - Yle Areena page for video file
#
# The following external binaries have to be available in path:
# zsh    - this is a zsh script
#        - zsh is assumed to be in /usr/bin/zsh, OSX has it in /bin/zsh,
#          edit as appropriate     
# yle-dl - for downloading
#          http://aajanki.github.io/yle-dl/
# ffmpeg - for converting
#          http://www.ffmpeg.org/
#          (probably available via your system's package manager)
#
# (c) 2015 Ola Rinta-Koski
#
# TODO:
# - handle multiple subtitle languages (for now, none or 1 language assumed)
# - what to do if FLV/SUB/M4V file exists? clobber (like now), or not?
# - this functionality should really be part of yle-dl, so consider
#   this a quick stopgap hack
#
# v1.0

if [[ "$# -ne 1 ]]
then
    echo "Usage: $0 [url]"
    exit 1
fi

title=$(yle-dl --showtitle $1)
target=${title}.m4v
flv=${title}.flv

yle-dl $1
subs=$(ls ${title}*.srt)

echo "Target ${target}"
echo "Subs $subs"
echo "FLV $flv"

if [[ -e $flv ]]
then
    if [[ -e $subs ]]
        ffmpeg -i ./"$flv" -i ./"$subs" -map 0 -map 1 -c copy -c:s mov_text ./"$target"
    else
        ffmpeg -i ./"$flv" -map 0 -c copy ./"$target"
    fi
    if [[ -e $target ]]
    then
        echo "Converted $flv -> $target, removing source file(s)"
	rm "$flv" "$subs"
    else
        echo "$flv -> $target conversion failed."
    fi
else
    echo "$1 download failed."
fi
